### ISSUE TITLE
cold lightstrip help needed (with mdl file)

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#100]
@TeamSpen210 & @BenVlodgi 

MARK THIS DAY ON THE CALANDAR, the cold lightstrip is finally about to make it's way into the bee2 editor

i'm implementing the cold lightstrip so you don't have to. I need some help with it.

how do i edit 3ds files i need to change the model pti uses so it looks like a cold lightstrip. 

![preview0240](https://cloud.githubusercontent.com/assets/11165643/9158191/19d364da-3ee0-11e5-87d5-4980a4cf577b.jpg)

also i have a suggestion of something you should implement into the compiler to work with the VBSP. make a way to override the texture applied to the wall, ceiling, or floor within the voxel that a item is placed on. this will solve the problem of textures not aligning up with the cold and warm lightstrips, and the regular lightstrips on the ceiling properly.

**Comment by TeamSpen210** [comment]
You want to edit the associated instance, not the model. Change the prop_static's skin to want you want.

**Comment by ellingtonisland** [comment]
@TeamSpen210,

i am talking about the model the PTI editor shows in the editor when you place these in your map, it is warm,

image of 3d model i want shown in pti.

![light_panel_cold](https://cloud.githubusercontent.com/assets/11165643/9158295/52b58bfa-3ee2-11e5-8b64-173003d799f4.jpg)

**Comment by ellingtonisland** [comment]
@TeamSpen210 i need help to edit the actual .3ds file to make a color edit to the 3d model itself that the PTI editor uses as you edit the map in PTI and place lightstrips on the wall in pti. i need to change the color of the texture so it looks like the photo in the post above, the current one is for the warm white lightstrip

**Comment by TeamSpen210** [comment]
The PeTI doesn't use the .3ds files, although that's what's typed into editoritems. You should extract the .mdl model from the dlc2 VPK, and reskin it to use a different texture.

**Comment by ellingtonisland** [comment]
@TeamSpen210 

i have the .mdl file, now what software do i use to edit and reskin it?

**Comment by ellingtonisland** [comment]
having problems with the decompiler recompiling the mdl, will let teamspen210 handle this upon release

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum @TeamSpen210 

I have managed to re-skin the mdl. file that is required in order to get the "Cold Light Strip PeTi Model". Basically i maded the "mdl." to use my custom VTF texture i edited on photoshop. This is what i done:

1- Used "xvi32" to open "light_strip02.mdl" (The one from the warm light strip).

2- Changed the name from "light_strip02.mdl" to "light_strip03.mdl" (This prevents the PeTi editor from keep using the Warm Skin).
![xvi32](https://cloud.githubusercontent.com/assets/12244376/16541958/37f9dc9a-406b-11e6-8d59-989b736282e9.png)

3- Changed the name to "light_strip03.3ds" where the Editoritems indicates the using model for it:

![colddd](https://cloud.githubusercontent.com/assets/12244376/16542058/cfc74712-406e-11e6-8dca-6172927c1d15.png)

4- And here is the final result, the three Light Strips Variations in one item, each one with their custom models:

![light_strip_variations](https://cloud.githubusercontent.com/assets/12244376/16542081/e0697724-406f-11e6-9c4e-6877b60a69e2.png)
![colddw](https://cloud.githubusercontent.com/assets/12244376/16542073/828bb1ee-406f-11e6-8dee-b378cc9b0add.jpg)
