### ISSUE TITLE
Original clean coop exit door does not open if the door is set to start locked.

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#1220]
![20161219101310_1](https://cloud.githubusercontent.com/assets/18079316/21299160/e7c5d8d4-c5d3-11e6-87f8-cb7c4210692a.jpg)

![20161219101316_1](https://cloud.githubusercontent.com/assets/18079316/21299167/0686a64a-c5d4-11e6-87a2-e5b1ea3e1a75.jpg)

**Comment by LautaroL20** [comment]
Do not add the "Development Version" label unless you were using an item thats currently unavailable into the public PRL23. Also, its funny because this is the second invalid issue of the day. Exit Door will never open if you select "Start looked" u wheely, and i don´t see any buttons connection in your screenshot...

**Comment by ZombiePwner1** [comment]
Can u also come online?

**Comment by LautaroL20** [comment]
Ok.
