### ISSUE TITLE
Will a Wheatley style be added?

### ISSUE THREAD

**Issue by harritron2k2** [TeamSpen210/BEE2-items#131]
Will a Wheatley style be added soon (After the art therapy style since it's still in development)? You could make a generator (like the debris in the overgrown goo pits) to make the walls that are not portable randomly create holes in them like in all the Wheatley tests. We already have bottomless pits and voice selection, but we need a monitor. Good work on the mod, it's wonderful!

**Comment by TeamSpen210** [comment]
I can't just make non-portalable surfaces have holes for two reasons: If the map had gels in it, they wouldn't be able to go on those surfaces - potentially breaking the puzzle. In addition, due to the way PeTI exports walls the compiler doesn't actually know which surfaces are "inside" the map, and which are facing outside. If I converted walls indiscriminately, there'd be leaks everywhere.

There will definitely be a Wheatley style, but there's lots of other stuff I should finish first.

**Comment by jccreszMinecraft** [comment]
I'd say automatically creating a toolsblack or nodraw box around the test
would fix the "Leaks"

On Wed, Oct 28, 2015 at 5:47 PM, TeamSpen210 <notifications@github.com>
wrote:

> I can't just make non-portalable surfaces have holes for two reasons: If
> the map had gels in it, they wouldn't be able to go on those surfaces -
> potentially breaking the puzzle. In addition, due to the way PeTI exports
> walls the compiler doesn't actually know which surfaces are "inside" the
> map, and which are facing outside. If I converted walls indiscriminately,
> there'd be leaks everywhere.
>
> There will definitely be a Wheatley style, but there's lots of other stuff
> I should finish first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamSpen210/BEE2-items/issues/131#issuecomment-152004854>
> .
>



-- 
[image: Ice Network 2014]

**Comment by harritron2k2** [comment]
Ok then I guess skip the holes, I'll just export it to hammer then add extra details in it
