### ISSUE TITLE
bottomless pit update: suggested fog fix

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#150]
@BenVlodgi & @TeamSpen210 

take a look at this after my update to the pit generation files, that BTS hole looks ominous!!

![preview0004](https://cloud.githubusercontent.com/assets/11165643/11605758/b5c6a91e-9ad5-11e5-9690-e5a609ebd6b2.jpg)

how i got the fog correct

extended all the pillars and parts of the pit except the skybox down to twice their length

extended the skybox itself down to the point where it was over 10,000 of valves meansurement unit in hammer deep.

adjusted the fog control in the skybox to the following settings

color - primary and secondary black
second fog start distance 4000
first 512

some bugs still exist like 

cubes won't sometimes get teleported into skybox and will dissapear when they hit floor

pit textures need to be changed to match current BTS wall textures

texture used for top first voxel needs to be changed too.

**Comment by TeamSpen210** [comment]
The problem with this is that the skybox fog settings should be the same as the map's settings - otherwise you'll get inconsistent fog if you make a tall map, and look at the pit from a distance. I also want to limit the size of the pit as much as possible (for FPS reasons, and so cubes don't take too long to respawn).

**Comment by ellingtonisland** [comment]
next release will vastly improve pits - case closed
