### ISSUE TITLE
Make Bottomless pits work on deep pools

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#159]
@TeamSpen210 and @BenVlodgi 

here is some images to explain how to solve some bugs with the bottomless pits, should be easy for the compiler to pull off. also <b>Light needs to pass from skybox into map and shadows from the map into the skybox so it looks even between the pit and the map if possible.<b/>

![pit 1](https://cloud.githubusercontent.com/assets/11165643/11630791/1218ddec-9ccd-11e5-87aa-7c6ea40e0fec.jpg)

how they should really work

![pit 1 - copy](https://cloud.githubusercontent.com/assets/11165643/11630795/148fd95e-9ccd-11e5-9b48-c5097f736066.jpg)

**Comment by TeamSpen210** [comment]
I can't make paint, lasers or any other special stuff go through skyboxes. Valve needs to specially code that into the game.

I'll make bottomless pits work for 2+ deep pools, but I won't extend the floor any more - it's quite complex to do, and unnecessary. The real problem currently is that trigger_hurt only activates every 0.5 seconds, so you fall to the bottom before dying.

**Comment by BenVlodgi** [comment]
Remove the trigger hurt
Add a fade to black kill the player at the end of the fade... That's how it's done in the bts 

It might be possible to activate a view proxy on the player when they hit the trigger. The view proxy would be attached inside a box of skybox we also spawn spawn a box of skybox which would all be patented to to a physbox in large open area box area outside the map
When the player hits the trigger in the pit (trigger teleport) the speed and direction of the player are captured and sent to a script, which then sets that speed and direction on the physbox ouside the map. The view proxy is activated
So then the skybox box your view is in, will fall through the floor (into the void)
But since it's all skybox, it will show the player falling through the skybox..... I litterally just had that whole idea right now. It's a total long shot, but would be super cool if it worlked

**Comment by TeamSpen210** [comment]
Currently, I'm actually using a trigger_teleport with reference entities to teleport physics objects into the skybox room. The scale is set to 1:1, and it ends up looking pretty good. I can enable the clients flag easily, the real problem is if the player looks upward after falling - they'll see the big open space above the skybox.

**Comment by jccreszMinecraft** [comment]
Camera direction locks? I've seen people control cameras in the Source
engine before.

On Tue, Dec 8, 2015 at 3:52 AM, TeamSpen210 <notifications@github.com>
wrote:

> Currently, I'm actually using a trigger_teleport with reference entities
> to teleport physics objects into the skybox room. The scale is set to 1:1,
> and it ends up looking pretty good. I can enable the clients flag easily,
> the real problem is if the player looks upward after falling - they'll see
> the big open space above the skybox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamSpen210/BEE2-items/issues/159#issuecomment-162818616>
> .
>



-- 
*-~=~-*
*Ice Network Entertainment Studios*
*-~=~-*

Chores in videogames are ridiculous!

**Comment by ellingtonisland** [comment]
@TeamSpen210 - i think you should go with ben's idea - and use @jccreszMinecraft idea of camera locks to control the camera when they fall into the pit so the camera redirects to looking down and they can't look up once they fall into the pit. 

i have another idea involving just 2 large world portals, what you do is surround the area the test chamber instances are in with a large empty black box to prevent leaks. then when the pit is placed you put a very large world portal that covers the entire bottom level of the map where the goo pit is that's linked into a world portal in the skybox, you generate the instances such as walls for the pit within the portal and when the player falls through they fall into the skybox and if they looked up they would see the test chamber through the world portal, this would solve the problem of gels and lasers and portal fires being stopped by the skybox.

**Comment by BenVlodgi** [comment]
@TeamSpen210 Oh, perfect! I thought the skybox was 16-1, which is why I suggested the fun complicated method.
It sounds like then, using the teleports and landmarks, you're almost set.... viewproxies can also restrict view angles I believe

**Comment by ellingtonvengaboysmuseum** [comment]
see more recent issue - case closed
