### ISSUE TITLE
enhancement: make cubes explode when they fall down bottomless pits

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#180]
i have a suggestion... 

make cubes explode when they fall down bottomless pits 

it should be easy to do, create some gibs, parent them to the cube, use a trigger in the pit, when the cube comes in contact, dissolve and kill the cube instance a half second later, and then generate a explosion that throws the gibs all over the place, also you need to make it so the explosion sound plays  in the map so the player hears it.

**Comment by TeamSpen210** [comment]
Cubes never explode in Portal - if anything they'd dissolve. What they do is disappear into the skybox fog, which matches the actual Valve maps.

In any case, this is not easy to do - I'd need to take the current cube models and break them up into different pieces, and then probably make an interior for them (since that isn't visible in the model). Then I'd need to make new versions of the full cube models that use the gibs, modify every dropper to include them (since you can use BTS skybox in Old Aperture styles), and then pack all of that into the maps.
