### ISSUE TITLE
need help with custom music (packing)

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#184]
teamspen210 - what code do i need to pack the uvb-76 files and stuff

hopefully after doing this, this sound plays properly.

**Comment by TeamSpen210** [comment]
I just added something to make this easier in the next version. Just add a `"Pack"` property to the `info.txt` object, set to the path for the file (relative to the `resources/` directory in the package):

	"Music"
		{
		"ID"			"ELL_MUSIC_ITEM"
		"Name"			"Name"
		"Icon"			"music/icon.png"
		"Authors"		"ellingtonisland"
		"Description"	"..."
		"SoundScript"	"path/to/music.wav"
		
		"Pack"          "sound/path/to/music.wav"
		}

"SoundScript" is the value set in ambient_generic, which assumes the 'sound/' subfolder. For "Pack", you need to specify it since you can pack things like soundscript files which are in different folders.

**Comment by ellingtonvengaboysmuseum** [comment]
buzzer file prepared for next release - case closed
