### ISSUE TITLE
suggestion: reskin the model of the strip lights in the clean style etc to create a "off" variant

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#219]
suggestion: reskin the model of the strip lights in the clean style etc to create a "off" variant

then add logic to control them from buttons etc

i came up with a idea of using the delayer items to create a series of light strips that would come on in groups when the player entered the test chamber as an aethestic effect in one test

**Comment by TeamSpen210** [comment]
Why? What use would toggleable lights have? Darkness shouldn't be part of a puzzle.

**Comment by ellingtonvengaboysmuseum** [comment]
it's not part of the puzzle, it would be just for an aesthetic effect, it would be a simular effect to the lights underground that came on when the player entered the test chamber, except the lights in the clean would make the test start out dim kind of how it looks before the observation room light comes on upon entry, these would come on in groups using the delayer item to just be an aesthetic effect. there wouldn't be pitch black darkness upon entry.

**Comment by TeamSpen210** [comment]
The way those lights come on is actually by teleporting you from a dark map into a lit one. (Noclip in `sp_a3_jump_intro`.) Since lighting (aside from `env_projectedtexture`) is statically generated by VRAD, each combination of on/off lights needs to be pregenerated. For 4 light strips, 16 different lightmaps would need to be generated - you'd basically be restricted to 3-4 toggleable light strips in the entire map.

In addition, these named lights don't look as good. There's also a reason why there's no 'off' clean lightstrip model - the texture for that light is just a black rectangle with a white oval, using normal maps and the `Refract` shader to create the 3D appearance. You wouldn't be able to see anything if it was turned off.
