### ISSUE TITLE
Antline "Block Bar" Router

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#253]
This is the first one of a series of ideas I had in mind.

First off excuse me if this item can not be maded due to any incompatiblity, but I feel it necessary to expose this. In the case of not being able to make it works for Bee editor i would love to know its issues.

------------------------------------------------------------------------------------

Lets start with it:

block bars similar to light strips dimensions. ZERO entity count (This is main purpose), with the ability of influencing indicators and antlines.

It will be usefull to influence antlines. GIF:

![gif 1](https://cloud.githubusercontent.com/assets/12244376/12533763/171e5688-c21a-11e5-8c4f-f647b7156802.gif)

As well as indicators. Here is some GIFS:

![gif 3](https://cloud.githubusercontent.com/assets/12244376/12533768/4f7746d4-c21a-11e5-93d6-6eebb5c63d30.gif)

![gif 2](https://cloud.githubusercontent.com/assets/12244376/12533779/b0d24460-c21a-11e5-9d93-3ec34298298e.gif)

We could still be able to redirect the indicator if it has the feature to not interfere with each other block bar:

![we could still be able to redirect it if does not interact with each other block bar](https://cloud.githubusercontent.com/assets/12244376/12533788/1e0ae05a-c21b-11e5-9de7-235fa031ce52.png)

------------------------------------------------------------------------------------------------------

Of course you can make a similar item meeting some or if possible all of the features mentioned here.

**Comment by TeamSpen210** [comment]
This is doable fairly easily. The only problem is the last one - the collision behavior of lightstrips (and fizzlers, light bridges) is coded into the game, so I don't think I'll be able to allow it to intersect items.

**Comment by MicroElf** [comment]
Make a nice antline sometimes is so hard. Simply almost impossible in some situations move antline at the place it should be without adding unnecessary elements. So, any tools (especially zero entity count) will be helpful. Despite it can look like not a very important thing I think it actually is, because anlines that are placed in the very right spot help new player gather information about chamber fast and comfortable and move to the next step: solving puzzle. Mandatory for a good puzzle.
