### ISSUE TITLE
suggested enhancements for atlas and pbody in single player

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#259]
some suggested enhancements for atlas and pbody when either of them are used in single player

- [ ] make them explode upon falling into a goo pit or bottomless pit like they do in the coop campaign
- [x] fix their portal gun orientation (atlas is way off)
- [x] see if you can figure how to change the portal gun models if possible so the portal colors in single player will match the guns they use in Coop if one of the two bots is used in single player. 
- add a item like the camera's in COOP they waved at that triggers something when both of them come near it in coop or one of them comes near it in single player see if you can figure out how to implement their waving command into single player if possible.

**Comment by TeamSpen210** [comment]
For 1, I actually don't think you should see that - in singleplayer the player doesn't respawn, and time effectively rewinds. For that reason you probably shouldn't see yourself exploding - that'd just look really strange. 

Since GLaDOS complains so much about it, I don't think she'd want to implement gesturing as a testing element. I do need to make a security camera item, which would probably function as a player-detector.

**Comment by ellingtonvengaboysmuseum** [comment]
maybe add a item called a single player robot respawner and if it's added it will change the conditions for atlas and pbody making them explode upon death and they will re spawn from that tube instead of the elevator.

**Comment by TeamSpen210** [comment]
It's quite complicated to make players appear to respawn - Coop and SinglePlayer work fundamentally differently upon death. ChickenMobile made a script to simulate Coop respawning in singleplayer, but that requires modifying every trigger_hurt or other killing method to instead trigger logic. 

The player-model changing is really purely aesthetic, it shouldn't really affect the gameplay at all.
