### ISSUE TITLE
Fix this light strip annoyance!!

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#31]
Fix this light strip annoyance!! Photo gives description

![preview0027](https://cloud.githubusercontent.com/assets/11165643/8397962/fabc14ac-1dab-11e5-928a-172174f8f829.jpg)

the panels don't line up with the light strips like they did in the original un modded portal 2 PTI.

Fix this because it drives me nuts.

also do the same thing for the warm and cold variations and add the cold variation too and combine all three into one item in bee2, use one of the cold lightstrips in the entry corridor as seen in this second photo as a template to the cold version, the ones someone uploaded to Thinking with portals look too purple.

![preview0028](https://cloud.githubusercontent.com/assets/11165643/8397973/7ac29c7a-1dac-11e5-97da-160140288366.jpg)

**Comment by TeamSpen210** [comment]
I fixed that here: BenVlodgi/BEE2.4/@15b2e41beb0ab3d24891c1a3a871c3b05fee5b7d
There was a typo in the material name, stopping the compiler from recognising the 4x4 white walls. Currently though it won't correct floor or ceiling textures, or warm light strips since the PeTI doesn't change its tile textures for those.
