### ISSUE TITLE
[Suggestion] Improvements to P1 lights

### ISSUE THREAD

**Issue by ncrecc** [TeamSpen210/BEE2-items#324]
1. Make the light strips into those that emerge from the floor and ceiling in the original Portal:
![](http://images.akamai.steamusercontent.com/ugc/309992442581043942/BA48C5DA57721F95FDADDE5C93076E0D83E32858/)
![]
(http://images.akamai.steamusercontent.com/ugc/309992442581044177/204E81769B9F9147EBA69BF033390A9BDFF559D7/)
(besides, randomizing where the light holes are placed is never a good idea)
2. Add a non-warm square light object and have the square lights be sufficiently bright.
3. Allow the square lights to be movable like lasers/laser detectors.

**Comment by TeamSpen210** [comment]
1. I can't really make light strips work like those recessed lights, they function fairly differently (they follow around corners, and don't really work on walls).
3. The problem is that square lights on corners would be pressed up against neighbouring blocks - there isn't room for a side wall if it's on a corner.

**Comment by ncrecc** [comment]
Thanks for replying, although I have one more request:
Can you make the placement on the holes on the light strips actually match as they are seen on the editor? Randomizing the holes isn't a very user-friendly idea.
