### ISSUE TITLE
[Question] Signages automatically generated into "Entry corridors" 

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#411]
I just used a random placement of the "Signage" item, and afther that, im getting "Signages" into the entry corridors, is this a bug or it is made on purpose?
![20160313093307_1](https://cloud.githubusercontent.com/assets/12244376/13860182/dc379a4a-ec65-11e5-9e53-8374a39b28f3.jpg)
![20160313093643_1](https://cloud.githubusercontent.com/assets/12244376/13860207/f2a33320-ec65-11e5-81b4-178c8db0bca7.jpg)

**Comment by TeamSpen210** [comment]
This is unrelated to the item. Since Old Aperture doesn't have the large test chamber signs, the corridors use various signs to indicate test elements. In the first picture, the "future you" poster is added if 'danger' is present in the chamber. In the next pre-release I'll probably be adding more signs, since I made a bunch of custom versions for the signage item.
