### ISSUE TITLE
help needed: location of instance files for new bee2.4 pre releases

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#42]
i need the location of instance files for new bee2.4 pre releases and what to do to edit them because i have plans to create a new style that will be based off the 50's underground style that will majorly modify it to make it look like you time traveled to the 50's aperture. 

the style will be part of my mod called portal: past, present, future.

this style will be a majorly modified 50's underground style that looks like it's brand spankin new as if you time traveled to the 50's.

**Comment by TeamSpen210** [comment]
First, check 'preserve game resources' in the Development tab of the BEE2 options (file>options) and restart. That ensures any changes you make to the instances won't be overwritten when you export from the BEE2. The instances are in instances/BEE2/. To make a style show up, you need to make a package.

Packages are basically a zip file (or folder) with a text file named info.txt. A package must have an ID, something like "ELL_NEW_50S". Then you have a "Style" property in there which defines the style. Probably it'd be easiest to copy the styles/OldAp folder into your packages/ directory, and then delete everything except the 50s style definition. Change the IDs (Otherwise the BEE2 will get the two styles confused), but add the 50s style ID in the "base" property. That makes your style use 50s items if a unique version isn't defined. Look at the rest of the package to see how you add a variant of an item for your style.

Both styles and items refer to a folder in items/ or styles/ in the package directory. That contains the editoritems data and vbsp_config (which has directions for the compiler).

**Comment by ellingtonisland** [comment]
unnh, i will let you guys create this style, hammer is giving me fits when i try to test the modified instances.
