### ISSUE TITLE
[Question] Is it possible if you could bring back the unused adhesion gel TeamSpen210?

### ISSUE THREAD

**Issue by ZombiePwner1** [TeamSpen210/BEE2-items#424]

**Comment by TeamSpen210** [comment]
I can kind of. It'd need to be a 'start reversed' option or the like on the Reflection Gel item, since I can only have one custom gel item. Adhesion gel is actually Reflection Gel, Valve didn't implement much of the actual effects. You're not going to be able to walk on walls with it. (The methods other people have used to get it working won't work in the PeTI.)
