### ISSUE TITLE
Grating prevents the player from being able to leaving the cube in CO-OP

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#464]
Basically, players can not leaving cubes when they´re standing on a grate, or sometimes when they re in front of them.

---

GIF ive record while i am playing with FrozenDragon and trying to leave the cube on the floor by pressing every time "E" and does nothing:

![gif](https://cloud.githubusercontent.com/assets/12244376/14403880/d921540a-fe3e-11e5-9c8a-6c5cb4974b1d.gif)

**Comment by Konclan** [comment]
Thats a very strange bug, were you able to replicate it multiple times?

**Comment by TeamSpen210** [comment]
I know what likely causes this, I'll change the way some optimisations are performed to resolve it.

**Comment by ZombiePwner1** [comment]
BTW that guy who was P-Body in the gif that was me

**Comment by LautaroL20** [comment]
@ZombiePwner1, True :)

**Comment by LautaroL20** [comment]
@TeamSpen210 - The Bee2.4 grate is seriously causing weird things.....

**Comment by LautaroL20** [comment]
I might try downgrading my grapichal drivers to see if i can resolve the huge fps downgrading, these companies tends to releasing many useless upgrades and that may cause issues sometimes...

**Comment by LautaroL20** [comment]
Not a driver problem.

**Comment by LautaroL20** [comment]
> I know what likely causes this, I'll change the way some optimisations are performed to resolve it.
That is the last hope that may resolve all the bee2.4 Grating issues. Hope you look into this as soon as you got the time. Be sure to let me know when you fix it so i can start using Bee2.4 again.

**Comment by TeamSpen210** [comment]
The specific optimisation is with the `func_clip_vphysics` used to make grates non-solid to physics objects. One entity is used for every tile originally, which is rather wasteful. I made the compiler just use one entity per 4x4 cube of space, so grates don't use up as many. That might be causing the problems, since a grate on the floor and wall would use the same entity.

I'll write some more intelligent logic, so only contiguous rectangular areas get merged together.

**Comment by LautaroL20** [comment]
Im happy to say this bug is finally solved now. Added the fixed lavel for next release.
