### ISSUE TITLE
add style var to remove entry and exit corridors

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#465]
add a style var to remove entry and exit corridors and make the elevator take you directly to the test chamber. 

this will be used eventually for creating custom entry corridors with my test signage item and some other items like a BTS re texturing item etc.

**Comment by TheReviewers** [comment]
Custom Corridors? Like how!?

**Comment by Konclan** [comment]
So there would be just an elevator where the door goes directly to the chamber without a chamber lock? Wouldn't that mean you need a sign object as well? I guess that would work but I don't see the point.

**Comment by TeamSpen210** [comment]
I don't think this would work that well. The corridor space would still be taken up regardless of the size of the corridor. It also won't work with Old Aperture and Portal 1 styles, since the entry elevator doesn't actually use a door. (It could potentially break maps if you're able to go back into the entry room, or can access a fizzler. The corridor in Old Aperture style also helps disguise the worldportal link into the camber - if the door was directly on the outside wall, it'd might be more obvious that the chamber doesn't actually fit in the exterior room.

**Comment by TheReviewers** [comment]
@TeamSpen210 Its No Point Of Disguising It, I Made a large Chamber in lenght, And It Still Looked Small From Exterior XD, Sorry
