### ISSUE TITLE
suggestion: other uses for logic used to design catwalks in PTI

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#50]
i like how you had pti generate catwalks with ant lines. I just thought of some other uses for the method you used to generate catwalks that could be used to pull off some other cool stuff

- use same method to generate diversity vents, but combine the item that generates the vents with the lift logic in PTI so you can extend it out from the wall and have bends mid air etc. in the test (best you combine the tubing and triggers to push items through the tubing in the same instances to prevent bugs)
- use the same method to generate a line of crushers that are timed like in the coop course that is just before the course with that giant fan in it.
- in a reconstructing style use this to generate a nice looking wall of falling panels as seen in sp_a2_catapult_intro when glados knocks those black ones off the wall by pushing them out with new white panels. make it so when one end is connected up to a trigger it will start the process of knocking down the overgrown panels in a line.
- use the same method to generate management rails and add cores to attach to them with voice lines for aesthetics.

**Comment by TeamSpen210** [comment]
Vactubes will use a similar method, but not exactly the same. Instead of placing corner pieces, you place straight sections, and t/y splits and joins. I might actually do the lift-logic thing, that should work fine.

This method won't work for anything that occupies space behind the wall, since that needs the PeTI to hollow out the blocks to fit the falling panels or crushers. I don't think I'll be making a sequential falling-panel item, but instead make an item which has the same effect (a permanent flip panel). Then in Reconstructing styles it'll work like those replacement panels.

I might make management rails, but the rails won't have cores since that would make the maps incompatible with Portal 2's plot.

**Comment by Konclan** [comment]
Wait, but arn't you considering cores in maps now?

**Comment by TheReviewers** [comment]
@TeamSpen210 Whats the point of managment rails then?

**Comment by TeamSpen210** [comment]
I'm not. Cores might appear on monitor screens if the appropriate voiceline is set, bur outside of that no. It's a really bad idea to have cores inside a map, in places acessable by players - what happens if you put them in goo? GLaDOS should probably also react to random cores invading her chambers.

**Comment by TheReviewers** [comment]
@TeamSpen210 If You Place Them In Goo, They Die...

**Comment by TheReviewers** [comment]
@TeamSpen210 And the map will restart

**Comment by TheReviewers** [comment]
if you can do that

**Comment by Konclan** [comment]
Well just don't allow the player to pick up cores
