### ISSUE TITLE
Spawn/End object

### ISSUE THREAD

**Issue by corrupt21** [TeamSpen210/BEE2-items#502]
This will do what you think it does, add a spawn point or add an end point. You could make it if the spawn is placed, it will destroy the spawn door, and destroy the exit if the exit is placed.

**Comment by TeamSpen210** [comment]
You really need specific detailing and design to make spawn points - level design wise it looks really wrong if a level starts or ends abruptly inside a map. It also hurts continuity since the next map almost certainly won't be in the exact same spot.

A future thing I've been implementing is the ability to place exit/entry doors on floors and ceilings, converting them to use a 90° bend corridor. That might take care of some of the use-cases for this as an item.

**Comment by TheReviewers** [comment]
@corrupt21 I Already Suggested this
