### ISSUE TITLE
Gel Plates...

### ISSUE THREAD

**Issue by TheReviewers** [TeamSpen210/BEE2-items#506]
I Dont Really Understand how gel can push you to the sky... maybe you can make a wooden push platform thingy... atleast for 1980 style

**Comment by Konclan** [comment]
Yeah the gel always confused people because it doesn't look like it should work like a faithplate.

**Comment by TeamSpen210** [comment]
You can use the dropdown on the right-click menu to switch it witch a mechanical variant. The idea for the gel is something like this: regular gel is a thin layer spread on a surface. The gel-plates are a solid block of gel, which magnifies the effect to the point where you get thrown at a location.Since it's so thick, water can't wash it away.

**Comment by TheReviewers** [comment]
@TeamSpen210 Alright Then...
