### ISSUE TITLE
[Question] Is it possible to implement on Bee2.4 to have P2 Valve background screenshots during the loading of a PeTi map?

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#840]

**Comment by TeamSpen210** [comment]
Unfortunately, no. Since those loading screens happen before the map is loaded, the game can't read from the map to figure out which one to use. Instead they're determined based on the map name - `sp_a1_` - `sp_a4_` . We can't change the PeTI map name, so this is the one thing that's impossible to do.
