### ISSUE TITLE
[Prl22 Bug] 70s' invisible exit barriers, leaks and corridor issues

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#861]
Working on my latest map I noticed that there were some issues with some of the exits and corridors, and settled for 1/1, which always seems to work. Now I've gotten around to testing which corridor and exit combinations actually have issues, and what the issues are. First off I'll just say that exit 1 works properly with all corridors.

**Invisible exit barriers**
When the exit is connected to any input in order to open, exits 2, 3 and 4 all have an issue with an invisible barrier blocking the player's access to the exit. This is the case for all entry corridors. You have to crouch, and go under the more or less invisible barrier in order to exit. I say 'more or less', because the barrier isn't actually completely invisible. As you'll notice on the images below, there's a thin black or brown (depending on the chosen exit) horizontal line across the middle of the exit door, and I'm guessing this is the barrier that blocks the exit. You'll probably have to click the images to see them full size in order to even spot the lines on these images.

Exit 2 (brown line):
![exit 2](http://i.imgur.com/LIB3e52.jpg)

Exit 3 (black line):
![exit 3](http://i.imgur.com/542yyFq.jpg)

Exit 4 (black line):
![exit 4](http://i.imgur.com/YwnCHrO.jpg)

Exits without inputs seem to work properly. 

**Leaks**
If either of exits 2, 3 or 4 are selected, and have an input, there occurs a leak, which is visible when entering the chamber:
![leak visible at entry](http://i.imgur.com/wlWb32g.jpg)

as well as on the exits (likely the source of the leak), at the bottom of the door:
![leak visible below exit](http://i.imgur.com/gnDcd84.jpg)

This is the case for all corridors.

This effectively renders exits 2, 3 and 4 useless, since there isn't a single corridor combination with them that works without issues.

**Corridors issuing portal guns**
Entry corridors 5, 6 and 7 (regardless of exit chosen, so this is an issue also for exit 1, which otherwise is working properly) are issuing portal guns on entry to the chamber. This is true even if the portal gun is used as a test element, and the player starts without a portal gun, as can be seen on this picture:
![portal gun at entry](http://i.imgur.com/uvWDNp8.jpg)

When walking into the exit, I got issued an orange only portal gun during this test. If my test had been intended to not have any portal guns until later on, these entries would ruin it.

**Comment by cartman1337** [comment]
I said earlier that exits left open, without inputs, did not have issues. Turns out that's not quite true. When the exit has no inputs, it is left wide open. So open, in fact, that the door is completely removed, only the fizzler behind is left.

Looking at this picture, can you tell that the corridor to the left is actually the exit, and the one to the right is not?
![70s open exit without doors](http://i.imgur.com/X5qHi3O.jpg)
This will happen with all four exits.

Here is how it should look like. This is from 60s style:
![60s open exit with doors](http://i.imgur.com/LDCxRDS.jpg)
Here it is obvious that the corridor to the left is the exit, because the exit door is visible.

**Comment by TeamSpen210** [comment]
Um, that's actually intentional. If you make the walls taller though, you'll be able to see the exit sign. The reason it's missing a door (when no inputs are connected) is to match with the resources Aperture has - they don't have much money, and so they're cutting corners whererever possible. If the door isn't needed, they leave it out. This also is done in P1 style (since they usually have exits leading directly to elevators there).

OH, I know the problem. Jump, you'll see that the line is actually the floor segment that's supposed to fill the leak in 'door' mode. The portalgun is a remmnant from BEE2.2.

**Comment by cartman1337** [comment]
You're right. Should be lowered to floor level, then.

![Floor in the air](http://i.imgur.com/mIu9OuA.jpg)

Fair enough about the exits. Never really thought about them being so much worse off in the 70s than they were in the 50s, 60s, 80s and later on, where the exit doors were still put in, even if it was left open.

**Comment by cartman1337** [comment]
About the open exits again. In Portal 1 style there is a very noticeable difference between the exit and a corridor with fizzler, even if the door in the exit is gone.

![Portal 1 open exit](http://i.imgur.com/rQ1YQQ4.jpg)

**Comment by TeamSpen210** [comment]
For 80s era, they were working on robotics, so I expect the doors would be cheap then. There's actually a number of things that change like that to show the lack of resources - instead of the blue finished wood here unfinished plywood is used: 
![blue_wood](http://i.imgur.com/LDCxRDS.jpg)
Also buttons aren't embedded into the floor anymore, just put on top.

Maybe I should add a flat 'exit' overlay on the floor in front, or make the compiler generate plank signs on the sides if needed.
