### ISSUE TITLE
[BTS] Add option to change grating to square beams

### ISSUE THREAD

**Issue by corrupt21** [TeamSpen210/BEE2-items#868]

**Comment by TeamSpen210** [comment]
There's a reason I didn't do that - Squarebeams models are way too large, cubes would easily fit through them. (They're 1/2 a tile in size). I might want to change it to the grating seen at the top of Test Shaft 09 (where all the large shock absorbers are). That's one of the few examples of BTS grating is. I might alternately switch it to squarebeams with a grate inside it (like the one you're thrown through before the moonshot).

**Comment by TeamSpen210** [comment]
Actually this won't work sensibly. The Test Shaft 09 grating is the same as Clean style. Squarebeams don't work since they're exactly on the 1/2 grid - putting grating in front of lasers or light bridges would make the laser need to pass directly through the beams. That can be done, but it looks weird. Additionally there's issues with texture clipping in corners.
