### ISSUE TITLE
[PRL22 Bug] Bee2.4 will crash if there is a folder with an "info.txt" inside the Packages folder, application should read "ZIP Files" only

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#918]
It looks like Bee2.4 also reads folders that are inside the packages folder. If there is a folder inside the packages folder that contains an "info.txt", it will make beemod crash.... Aplication should only read "ZIP Files", not folders.

Folder that makes the aplication crash:
![crash](https://cloud.githubusercontent.com/assets/12244376/19355554/2436fd10-9141-11e6-98ba-8564a74bee23.png)

# CRASH REPLICATION STEPS:  

1. Create a folder called "light strip", then add an "Info.txt" extracted from any package.
2. Add that folder inside the one where packages are.
3. Launch Beemod.
4. Happy crashing!

**Comment by TheDarkBomber** [comment]
No, it should NOT be .zip files only. You are presuming, that since it is a different type, it is not readable. However, when I added my custom items as a folder to PR22, they worked fine. There is already a light_strip file, plus just adding the .info file is not enough, it also needs more file paths in the package.

**Comment by LautaroL20** [comment]
So, aparently beemod also reads folders the same way as a zip package? Didn´t notice that before.

**Comment by TeamSpen210** [comment]
It's very useful, since that's the way  I do all the development. You just point the app to this repro, and it'll directly read all the data.
