### ISSUE TITLE
help needed with new fizzler "force field"

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#98]
@TeamSpen210 and @BenVlodgi  

i have created a new fizzler type, i call it a force field and i need help with finishing it. here is a photo of it in game, also there is a solid invisible block that is showing up with the fizzler.

![preview0093](https://cloud.githubusercontent.com/assets/11165643/9102002/a425b084-3bbb-11e5-9bae-bd150d1ab7ef.jpg)

invisible bug block.
![preview0096](https://cloud.githubusercontent.com/assets/11165643/9102005/a76a7c66-3bbb-11e5-8bb1-f3698214da83.jpg)

i need help with the vbsp_config file creating a few brushes, this is the code in the current vbsp_config file

```
"Conditions"
	{
	"Condition"  
		{ 
		"instance"	"instances/BEE2/clean/items/ei/ff_base.vmf"  
		"result"  
			{
			"Has"
				{
				"Fizzler"	"1"
				"EI_ff"	"1"
				}
			"CustFizzler"
				{
				"ModelName"		""
				"UniqueModel"	"0"
				"Brush"
					{
					"Name"		"fizz"
					"Left"		"BEE2/fizz/ellingtonisland/clean_ff_left"
					"Center"	"BEE2/fizz/ellingtonisland/clean_ff_center"
					"Right"		"BEE2/fizz/ellingtonisland/clean_ff_right"
					"Short"		"BEE2/fizz/ellingtonisland/force_field"
					"Keys"
						{
						"classname" 	"trigger_portal_cleanser"
						"Spawnflags" 	"4096" // nothing						
						"visible"		"1"	
						"usescanline"	"1"						
						"StartDisabled"	"1"
						}
					}
				"Brush"
					{
					"Name"		"clip"
					"Left"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Center"	"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Right"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Short"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Nodraw"	"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Keys"
						{
						"classname" 	"func_brush"
						"Spawnflags" 	"2" // Ignore +USE
						"solidity"		"0" // Toggle
						}
					}
				"Brush"
					{
					"Name"		"clip"
					"Left"		"tools/toolsinvisible"
					"Center"	"tools/toolsinvisible"
					"Right"		"tools/toolsinvisible"
					"Short"		"tools/toolsinvisible"
					"Nodraw"	"tools/toolsinvisible"
					"Keys"
						{
						"classname" 	"func_clip_vphysics"
						"Spawnflags" 	"2" // Ignore +USE
						"solidity"		"0" // Toggle
						}
					}	
				}
			}
		}
	}
```

i been trying to get the field to play the sound the lightbridge makes when walked on but i am having no luck. 

i need to create a brush that will block paint from passing through and also allow the field to be painted when active like a lightbridge

and i need a brush that will prevent light bridges and lasers from passing through it when active.

type the code you would use exactly as you would put it into this vbsp_config file so i know what to do.

if the fizzlers main vmt file needs to be modified, here is the source code of it

```
SolidEnergy
	{
	$basetexture "effects/fizzler_ripples"
	$flowmap "effects/fizzler_flow"
	$flowbounds "effects/fizzler_underground_wide_center_bounds"
	$FLOW_NOISE_TEXTURE "effects/fizzler_noise"
	$FLOW_UVSCROLLDISTANCE "50"
	$FLOW_TIMEINTERVALINSECONDS 15
	$FLOW_NOISE_SCALE 0.0013
	$FLOW_LERPEXP 3
	$FLOW_WORLDUVSCALE 0.00032
	$FLOW_NORMALUVSCALE 0.004
	$surfaceprop "hard_light_bridge" // Makes electric sounds when stepped on
	"%keywords" Portal2
	$translucent 1
	$additive 1
	$FLOW_COLOR "[0.196 0.196 0.196]"
	$FLOW_VORTEX_COLOR " [0.232 0.232 0.232]"
	$FLOW_VORTEX_SIZE 50
	$intensitynoise 1
	$totalintensity 1
	"srgb?$outputintensity" 3.3
	"!srgb?$outputintensity" 1.7
	Proxies
	{
		FizzlerVortex
		{
			}
			Sine
			{
		sineMin 0.95
		sineMax 1.0
		sinePeriod 0.1
		resultVar $intensitynoise
			}
			Multiply
			{
		srcvar1 $flow_color_intensity
		srcvar2 $intensitynoise
		resultvar $totalintensity
			}
			Equals
			{
		srcvar1 $totalintensity
		resultvar $flow_color_intensity
			}
		}
	}

```

**Comment by TeamSpen210** [comment]
I'd suggest first building a hammer-only test map, and figure out what brush entities you'll even need to block the things you want. I don't know if it's even possible to create clips to block light bridges or lasers specifically. For paint, you can use a trigger_paint_cleanser, or a func_clip_vphysics to block just the paint bombs (see global_ents to check what filter name to use).

For the sound, I think it helps if you set 'solidbsp' to 1 in the player_clip_electric brush. Surfaceprop won't do anything in the fizzler, since it isn't solid.

**Comment by ellingtonisland** [comment]
to block the lightbridge, laser, and funnel, isn't their a way to make it act like a normal wall, but invisible.

would the Block Bullets, Invisible, or no draw textures work for blocking or 

do you know how to create a custom vmt to form a texture that blocks light and lasers and funnels

how does the light bridge texture allow paint on it. 

where are the portal 2 texture files located. i may look at the texture for a normal wall panel.

**Comment by TeamSpen210** [comment]
You can try any of those textures instead of the player_clip_electric in the func_brush. What exatly do you want to block, and let through? If you just want to stop everything, just use the nodraw textures (you might want to extract the original nodraw texture, and make a modfied version with the lightbridge $surfaceprop).

The Portal 2 testing elements are specifically coded to behave how they do, it's difficult to change or manipulate them. Light bridges would be specifically coded to allow paint, paint on bridges uses totallly different materials compared to on brushes.

Portal 2's textures are in the VPK files. Open the portal2/pak_01_dir.vpk file with GCFscape to look at them. Some textures are in the dlc1 and dlc2 folders instead. DLC1 has extra content for the Art Therapy course, and DLC2 has all the puzzlemaker models and textures.

**Comment by ellingtonisland** [comment]
we have a working new test element @TeamSpen210 and @BenVlodgi 

i used blockbullets as the base brush and it now blocks everything. 

proof of concept besides player standing on it!! 

cube
![preview0104](https://cloud.githubusercontent.com/assets/11165643/9120900/0c9c24fe-3c4d-11e5-9ac0-523a10b35c60.jpg)

lightbridge and laser
![preview0108](https://cloud.githubusercontent.com/assets/11165643/9120921/29089942-3c4d-11e5-8c8d-89e4a310fd9d.jpg)

paint
![preview0103](https://cloud.githubusercontent.com/assets/11165643/9120943/3d3966b2-3c4d-11e5-8f45-c01f8b6e0d38.jpg)

now all i need is your help making it paintable. here is the current code i used to make it block the lightbridge and laser

```
UnlitGeneric
{
$basetexture "Tools/toolsblockbullets"
$solidbsp 1
//$alpha 0
"%compilenodraw" 1
$surfaceprop "hard_light_bridge" // Makes electric sounds when stepped on
}
```

what should i put in here to make it so paint adheres to it like a normal wall.

**Comment by ellingtonisland** [comment]
here is the real reason i created the force field, to contain something diabolical like this in a test chamber, just imagine a test where you have to solve it within a time limit before the force feild is disabled releasing this.

![preview0146](https://cloud.githubusercontent.com/assets/11165643/9125498/816fe8e8-3c6f-11e5-8c95-e3f31dd086f6.jpg)

also my vmt file has changed, here is the new one, it is still not allowing me to paint it, do you know of something to put into the code to fix this?

```
UnlitGeneric
{
$basetexture "metal/black_wall_metal_002c"
$solidbsp 1
//$alpha 0
"%compileBlockLOS" 0
"%compilenodraw" 1
$surfaceprop "hard_light_bridge" // Makes electric sounds when stepped on
}
```

**Comment by TeamSpen210** [comment]
I don't know if you can actually make invisible paintable things, I might have to try some things. Get rid of the %compilenodraw and blocklos, it should still block everything else but allow paint. The brushes will become visible again, but you might want to try setting 'rendermode' to '10' in the Keys section in the vbsp_config, to make it invisible again. If that makes the paint invisible, try setting 'rendermode' to '4' and setting 'renderamt' to '1' in the keys, so it's barely visible, but hopefully the paint is opaque.

**Comment by ellingtonisland** [comment]
i did what you said and tried rendermode and renderamt and both don't work, when i put in renderamt in the keys it was invisible still and the paint was blocked, but it did not paint the field. what is the exact code for rendermode and renderamount incase i got it wrong, here's what i put in

```
"Conditions"
	{
	"Condition"  
		{ 
		"instance"	"instances/BEE2/clean/items/ei/ff_base.vmf"  
		"result"  
			{
			"Has"
				{
				"Fizzler"	"1"
				"EI_ff"	"1"
				}
			"CustFizzler"
				{
				"ModelName"		""
				"UniqueModel"	"0"
				"Brush"
					{
					"Name"		"fizz"
					"Left"		"BEE2/fizz/ellingtonisland/clean_ff_left"
					"Center"	"BEE2/fizz/ellingtonisland/clean_ff_center"
					"Right"		"BEE2/fizz/ellingtonisland/clean_ff_right"
					"Short"		"BEE2/fizz/ellingtonisland/force_field"
					"Keys"
						{
						"classname" 	"trigger_portal_cleanser"
						"Spawnflags" 	"4096" // nothing						
						"visible"		"1"	
						"usescanline"	"1"						
						"StartDisabled"	"1"
						}
					}
				"Brush"
					{
					"Name"		"clip"
					"Left"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Center"	"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Right"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Short"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Nodraw"	"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Keys"
						{
						"classname" 	"func_brush"
						"Spawnflags" 	"2" // Ignore +USE
						"rendermode"	"4"
						"renderamt"     "1"
						"solidity"		"0" // Toggle
						}
					}				
				}
			}
		}
	}
```

**Comment by TeamSpen210** [comment]
I don't know if it's actually even possible to make a paintable brush with an invisible texture. You should probably make your own git repro for your items, that way I can send pull requests and similar things more easily.

**Comment by ellingtonisland** [comment]
but what is the exact code for "rendermode" and  "renderamt" incase i got it wrong.

**Comment by ellingtonisland** [comment]
@TeamSpen210 

ok we HAVE made some progress, i figured how to paint it

paint on the fizzler

![preview0193](https://cloud.githubusercontent.com/assets/11165643/9141638/3b994154-3d08-11e5-9ce9-67bc1371ddfa.jpg)

but still we have some bugs that need fixing i will need your help with

![preview0187](https://cloud.githubusercontent.com/assets/11165643/9141661/6670de64-3d08-11e5-941b-2420356d7d2d.jpg)

see this lighter area in the fizzler, that is caused by the brush that the paint is sticking to being the same width as the fizzler texture brush, do you know how to change that is it is just a tiny bit wider so the surface paint will attach to is above the fizzler texture surface. 

and when the fizzler is shut off and turned back on the paint returns, do you know how to put a paint cleanser in there that has inverted input that will clean it off right when it turns off

![preview0201](https://cloud.githubusercontent.com/assets/11165643/9141700/a4c99c50-3d08-11e5-820e-b26583039a5a.jpg)

tell me what you would put in the code exactly as you would put it in there, here is my code for the vbsp file

```
"Conditions"
	{
	"Condition"  
		{ 
		"instance"	"instances/BEE2/clean/items/ei/ff_base.vmf"  
		"result"  
			{
			"Has"
				{
				"Fizzler"	"1"
				"EI_ff"	"1"
				}
			"CustFizzler"
				{
				"ModelName"		""
				"UniqueModel"	"0"
				"Brush"
					{
					"Name"		"fizz"
					"Left"		"BEE2/fizz/ellingtonisland/clean_ff_left"
					"Center"	"BEE2/fizz/ellingtonisland/clean_ff_center"
					"Right"		"BEE2/fizz/ellingtonisland/clean_ff_right"
					"Short"		"BEE2/fizz/ellingtonisland/force_field"
					"Keys"
						{
						"classname" 	"trigger_portal_cleanser"
						"Spawnflags" 	"4096" // nothing						
						"visible"		"1"	
						"usescanline"	"1"						
						"StartDisabled"	"1"
						}
					}
				"Brush"
					{
					"Name"		"clip"
					"Left"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Center"	"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Right"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Short"		"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Nodraw"	"BEE2/fizz/ellingtonisland/player_clip_electric"
					"Keys"
						{
						"classname" 	"func_brush"						
						"Spawnflags" 	"2" // Ignore +USE						
						"solidity"		"0" // Toggle
						"rendermode"    "4"
						"renderamt"     "1"
						}
					}				
				}
			}
		}
	}
```

**Comment by TeamSpen210** [comment]
I'll need to add the ability to change the fizzler width to the custom compiler. To get rid of the paint, you'll need to send a RemovePaint input to the 'clip' when it's Disable-d in the base instance. Can you make a repro for this? That way I can get a copy easily, and try and fix these issues.

**Comment by ellingtonisland** [comment]
@TeamSpen210  what is the exact code for the removepaint input i need to put into the vbsp

**Comment by ellingtonisland** [comment]
@TeamSpen210 also we have another problem, how do we fix paint not showing up on the other side of the field when painted.

![preview0211](https://cloud.githubusercontent.com/assets/11165643/9148325/356bc5b6-3d46-11e5-9b60-bccd9a1db061.jpg)

![preview0212](https://cloud.githubusercontent.com/assets/11165643/9148327/38b3dea2-3d46-11e5-95a3-2c75ade139a4.jpg)

**Comment by TeamSpen210** [comment]
The removePaint input goes in the `instances/BEE2/clean/items/ei/ff_base.vmf` instance, not in vbsp_config. Open the logic_branch there, and add an OnFalse output which triggers the RemovePaint input, with a target of 'clip'. Paint won't show up on the other side, that's probably actually a good thing (it's probably really a bug that light bridges simultaneously paint both sides). Can you please put this in a repository somewhere, I can fiddle with it myself then.

**Comment by ellingtonisland** [comment]
i just discovered some more bugs, i got the paint remover working through. 

first bug: paint should show up on both sides if field is painted since it's a transparent field.

![preview0215](https://cloud.githubusercontent.com/assets/11165643/9151282/feef3100-3dca-11e5-84a5-fb8b2d13d2cd.jpg)

when viewed from other side paint should be able to be seen through it, but it doesn't.
![preview0216](https://cloud.githubusercontent.com/assets/11165643/9151285/2de07dd4-3dcb-11e5-8a02-828fdc49894c.jpg)

do you know how to fix this, i think it may not be able to be done. the reason you see the lightbridge with paint on both sides is it has a decal built into it that shows up when you apply paint to it. i had a idea for a different kind of fizzler as a backup if this one was buggy when painted, i will just make this one block paint and non paintable if this doesn't work. my new fizzler i came up with i call a gel suspension field and it will be non transparent and in the color of the corresponding gel and it will be solid just like the force field and it will have a brush to apply gel to it which will be invisible with rendermode 10, i discovered in rendermode 10 paint is invisible, but it still functions normally, i will need a way to apply paint to the thing in hammer or so.

bug: side of field is visible

![preview0219](https://cloud.githubusercontent.com/assets/11165643/9151287/4c2f3974-3dcb-11e5-8960-973f77279273.jpg)

same thing visible on normal fizzler

![preview0225](https://cloud.githubusercontent.com/assets/11165643/9151289/58c37dda-3dcb-11e5-9723-f7476842ff27.jpg)

do you know how to fix this with the side, it needs nodraw to be applied to the sides in the compiler i think.

**Comment by TeamSpen210** [comment]
You should probably make both items, a paintable fizzler would be pretty useful. Alternately you could make it fully opaque - light bridges and funnels actually use the same shader, so you could use those textures in addition. 

The fizzler sides are intentional, it ensures you can see fizzler fields from the side. Otherwise they would appear invisible at certain angles.

To make the paint entities, use the fizzModelPair condition result, like in the paint Fizzler item. Just set the start and end instances to the same as the default model. For the mid instance copy-paste the Paint Fizzler one, then add two info_paint_sprayers point inward from left and right. That should make them paint the fizzler.

**Comment by ellingtonisland** [comment]
i'm going to create the paint fields because the forcefield won't put paint on both sides correctly if painted with a paint dropper. i will need to make the info_paint_sprayers not show any particle splashes etc when the paint fields are painted.

**Comment by TeamSpen210** [comment]
Check the 'Silent' option on the sprayers, that will make them not show effects.

**Comment by ellingtonvengaboysmuseum** [comment]
item is near complete - topic will be looked at if needed for paint fizzler etc - case closed
